USE [master]
GO

/****** Object:  Database [TechInside]    Script Date: 21/11/2020 23:24:10 ******/
CREATE DATABASE [TechInside]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechInside', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TechInside.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TechInside_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TechInside_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TechInside].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TechInside] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TechInside] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TechInside] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TechInside] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TechInside] SET ARITHABORT OFF 
GO

ALTER DATABASE [TechInside] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TechInside] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TechInside] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TechInside] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TechInside] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TechInside] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TechInside] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TechInside] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TechInside] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TechInside] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TechInside] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TechInside] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TechInside] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TechInside] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TechInside] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TechInside] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TechInside] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TechInside] SET RECOVERY FULL 
GO

ALTER DATABASE [TechInside] SET  MULTI_USER 
GO

ALTER DATABASE [TechInside] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TechInside] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TechInside] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TechInside] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TechInside] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TechInside] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TechInside] SET  READ_WRITE 
GO

